import { Card } from './card'

export class Setup {
	shelters = false
	platCol = false
	spoils = false
	ruins = false
	horse = false
	coins = false
	debt = false
	potions = false
	VP = false
	embargo = false
	cubes = false
	tavernMats = false
	coffers = false
	villagers = false
	exile = false
	nativeVillage = false
	pirateShip = false
	island = false
	tradeRoute = false
	// minimum 10% chance to use shelters, 20% chance to use platinums/colonies
	numDarkAges = 1
	numProsperity = 2
	journey = false
	trashing = false
	estate = false
	plusCard = false
	plusAction = false
	plusBuy = false
	plusOne = false
	minusOne = false
	minusTwo = false
	minusDraw = false
	boon = false
	hex = false
	wishes = false
	prizes = false
	hermit = false
	urchin = false
	page = false
	peasant = false
	loot = false
	mirror = false
	lamp = false
	goat = false
	pasture = false
	pouch = false
	cursedGold = false
	luckyCoin = false
	wisp = false
	imp = false
	ghost = false
	zombies = false
	bats = false
	flag = false
	horn = false
	key = false
	lantern = false
	chest = false
	bane = false
	baneChoice: Card = new Card()
	obelisk = false
	obeliskChoice: Card = new Card()
	mouse = false
	mouseChoice: Card = new Card()
	market = false
	favors = false
	ally: Card = new Card()
	trait: boolean = false
	traitCard: Card = new Card()
	traitChoice: Card = new Card()
}
